### ISSUE TITLE
Document and publish MCA API

### ISSUE THREAD

**Issue by soichih** [perfsonar/psconfig-web#15]
This is just a reminder for the item that Marian has suggested
> 5. API to setup meshes and tests. While not critical we do have some use cases where computing meshes would work better than manual editing.

I should give instruction on how to 
1) generate non-expiring JWT token
2) URL for viewing the API doc
3) Sample code to access various APIs.

**Comment by soichih** [comment]
Sample API doc >https://soichi7.ppa.iu.edu/mca/apidoc

**Comment by ShawnMcKee** [comment]
Very nice.   On a quick glance it looks like this can support everything I was thinking about "scripting" from a central location.

Some quick comments/questions:

Some detailed examples showing how to use 'authorization' would be really helpful.  I guess that is on your list already.

You have an ma_override option on the Download auto-meshconfig.   Is there a similar option for Download meshconfig?   We may want to support over-riding that for some use-cases.

The the status /health checks, what kind of things are being checked?   You have 'ok' or 'failed'; does that mean if it is OK one or more dependent services where checked and found to work?  Is there additional (meta)data available if we get 'failed'?   Is there a way to pass along extended information like failure details?

I am interested in the New Adhoc Host item.   Is this to create a host that is not found from either the lookup service, OIM or GOCDB?   In effect, this is a way to register a host directly with the MCA?   Once it is added I assume it persists indefinitely?   What happens if this same host then does publish its data to the lookup service?  How does MCA handle having a host showing up from more than one "source"?

If I think of more questions or comments I will post them.  Thanks.

**Comment by soichih** [comment]
>  detailed examples showing how to use 'authorization' 

I have the curl example in https://github.com/soichih/meshconfig-admin#mca-api I can write more examples, or something similar in other languages.. Which language are you planning to write your script in?

> You have an ma_override option on the Download auto-meshconfig.

I forgot to document this for /config side. It should work on both /config and /auto. (so does the host_version parameter)

> The the status /health checks, what kind of things are being checked? 

For administrator (https://meshconfig-itb.grid.iu.edu/api/mca/health) it checks..

* api service itself is running
* mcache service caching service is running and cache is fresh
* can connect to the mongodb and at least one host is registered.

For publisher (https://meshconfig-itb.grid.iu.edu/pub/health) it checks..

* pub service is running
* profile cache service is running and data is fresh
* can connect to mongodb and at least one config is registered.

If any of these fail, you will see `"status": "failed"` and `"msg": "..."` containing what is failing.

There is also /health for auth service (https://meshconfig-itb.grid.iu.edu/api/auth/health), but this doesn't do much checking.. yet. You can query this just to make sure that the auth service itself is running.

For Adhoc host..
> Is this to create a host that is not found from either the lookup service, OIM or GOCDB? 

Yes

> In effect, this is a way to register a host directly with the MCA?

Exactly.

> Once it is added I assume it persists indefinitely?

Yes, it will be persisted.

> What happens if this same host then does publish its data to the lookup service? 

When that happens, the adhoc host will become a normal host, and at that point updating it no longer makes sense, because most information will be overridden by the cache service every hour. However, host has 2 sets of information 
* (LS info) hostname, sitename, host info, communities
* (MCA info) no_agent, toolkit_url,  MA endppoints.

You can continue making changes to the (MCA info) even after the host becomes *normal* host, because the information for (MCA info) doesn't come from sLS.

> How does MCA handle having a host showing up from more than one "source"?

The host found in the first datasource takes precedence as configured in `meshconfig-itb.grid.iu.edu:/etc/mca/index.js` So, based on the current configuration, if a host is found in global LS - with "atlas" (for example), that host information will take precedence over host information found in subsequent datasources. I have gocdb2sls service ("gocdb-oim") listed at the bottom, so it will only be used if the host is not found in global LS.

I hope this makes sense!

**Comment by ShawnMcKee** [comment]
Yes, this all makes sense and sounds like it works the way I think it
should.   Let me know when meshconfig-itb.grid.iu.edu has the new API stuff
and I can test it there.

Thanks,

Shawn

**Comment by soichih** [comment]
Ok great. All the API is already there and you should be able to test it.
Today is goc's itb release day so it might be bouncing throughout the day,
however.

Please let me know if I should document more examples (and which language).

Soichi

**Comment by apertome** [comment]
The API is largely self-documenting, but we should write some docs on how to get started using it and that sort of thing.

**Comment by apertome** [comment]
For the initial release, the API self-generated docs are sufficient here. Need to figure out how to update them.

**Comment by apertome** [comment]
Figured out how to build the docs; will likely add docs build to the script that builds the mca docker container so they are available in every deployment, as well as figure out a central place to host them.

Need to review whether/how they need to be updated to reflect changes we've made recently

**Comment by apertome** [comment]
4.1beta1 API docs are finished
