### ISSUE TITLE
psconfig-web-admin-* 5.0.8 / mongodb 4.0.3 dependency issues on EL9

### ISSUE THREAD

**Issue by mty22** [perfsonar/psconfig-web#232]
I'm currently upgrading a handful of servers from EL7 to EL9 and in this scenario, pSConfig Web Administrator (PWA) is in scope.

On a development instance and following instructions from https://docs.perfsonar.net/pwa_install_rpm.html#installing-pwa-from-rpms -- I ran into this dependency issue when installing the following packages:

```
perfsonar-psconfig-web-admin-ui-5.0.8-1.el9.x86_64
perfsonar-psconfig-web-admin-publisher-5.0.8-1.el9.x86_64
```

specifically as these packages require either of the following dependencies:

```
mongodb-org <= 4.0.3
mongodb-org-server <= 4.0.3
```

Which is evident in the spec file on git tag v5.0.8 (which is the latest release of PWA at the time of writing):

https://github.com/perfsonar/psconfig-web/blob/v5.0.8/psconfig-web-admin/perfsonar-psconfig-web-admin/unibuild-packaging/rpm/perfsonar-psconfig-web.spec#L58-L59

Unfortunately there is no upstream packages available for mongodb 4.0 on EL9 - https://repo.mongodb.org/yum/redhat/9/mongodb-org/ (4.0 packages remains for EL8), which ultimately means that PWA cannot be installed on EL9 using RPMs (instead of Docker).

**Comment by mfeit-internet2** [comment]
We discovered this while developing support for OL8 and will fix the dependency in 5.1.2 so it requires `<= 4.1.0` to catch bug fixes.

**Comment by mty22** [comment]
I appreciate the response @mfeit-internet2 

I see your commit here: https://github.com/perfsonar/psconfig-web/commit/660f7211a308fb16f6a5231407703b658315a085

However the only thing to keep in mind that MongoDB 4.4 is EOL as of 2024-02-29 (https://www.mongodb.com/legal/support-policy/lifecycles) and no longer receives security updates.

In addition, MongoDB 5.0 will also be EOL in 3 months time (2024-10-31).

Did the team have plans on reviewing support for MongoDB 5 or greater? (I ask as some R&E institutions have strict policies against running EOL software).

Thanks!

**Comment by mfeit-internet2** [comment]
We're aware the version of MongoDB PWA uses is past its expiration date.

MongoDB 4.2 was re-licensed in a way that's incompatible with the way the rest of perfSONAR is licensed.  Putting in the time to make PWA work with later versions we couldn't distribute didn't seem like a great use of resources, so we haven't.  It may well work as-is with newer versions; the RPM can still be installed by force if you want to try it out.

PWA is on its last legs for a number of other reasons and we're in the very-early stages of designing a replacement.  That will not use MongoDB at all because of the licensing and it's overkill for this application.
